name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Build the Docker image
      run: |
        TIMESTAMP=$(date +%s)
        docker build . --file Dockerfile \
          --tag ${{ vars.DOCKER_USERNAME }}/kv:${TIMESTAMP} \
          --tag ${{ vars.DOCKER_USERNAME }}/kv:latest
    
    - name: Push Docker image
      run: |
        docker push ${{ vars.DOCKER_USERNAME }}/kv:$(date +%s)
        docker push ${{ vars.DOCKER_USERNAME }}/kv:latest