name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Build and push Docker image
      run: |
        TIMESTAMP=$(date +%s)
        REPOSITORY=${{ vars.DOCKER_USERNAME }}/kv
        
        docker build . --file Dockerfile \
          --tag ${REPOSITORY}:${TIMESTAMP} \
          --tag ${REPOSITORY}:latest
        
        docker push ${REPOSITORY}:${TIMESTAMP}
        docker push ${REPOSITORY}:latest
        
    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
        repository: ${{ vars.DOCKER_USERNAME }}/kv
        readme-filepath: ./README.md
        short-description: "Lightweight, high performance key-value store with HTTP API. Built with ReactPHP and SQLite"