name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Build and push Docker image
      run: |
        TIMESTAMP=$(date +%s)
        
        docker build . --file Dockerfile \
          --tag ${{ vars.DOCKER_USERNAME }}/kv:${TIMESTAMP} \
          --tag ${{ vars.DOCKER_USERNAME }}/kv:latest
        
        docker push ${{ vars.DOCKER_USERNAME }}/kv:${TIMESTAMP}
        docker push ${{ vars.DOCKER_USERNAME }}/kv:latest
        
    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
        repository: ${{ vars.DOCKER_USERNAME }}/kv
        readme-filepath: ./README.md
        short-description: "A lightweight key-value store with HTTP API built using ReactPHP and SQLite"